#!/bin/sh
## bin2dec for shell in /home/jouvel_a/rendu/SHL_2016_shell
## 
## Made by Anthony jouvel
## Login   <jouvel_a@epitech.net>
## 
## Started on  Mon Jan  2 19:04:16 2017 Anthony jouvel
## Last update Mon Jan  2 20:32:57 2017 Anthony jouvel
##

if [ "$#" -ne 1 ];then
    echo "USAGE: $0 BinNumber" 1>&2
    echo "Convert binary number to decimal number" 1>&2
    exit 1
fi

for binary in $*
do
    if [ "${binary/[^01]}" != "$binary" ]
then
    echo "Error"
    exit 1
continue
fi
let value=2#$binary
echo -n "bin2dec($binary)="
echo $value
done
