#!/bin/sh
## bin2dec for shell in /home/jouvel_a/rendu/SHL_2016_shell
## 
## Made by Anthony jouvel
## Login   <jouvel_a@epitech.net>
## 
## Started on  Mon Jan  2 19:04:16 2017 Anthony jouvel
## Last update Tue Jan  3 12:42:59 2017 thomas vigier
##

if [ "$#" -ne 1 ];then
    echo "USAGE: $0 BinNumber" 1>&2
    echo "Convert binary number to decimal number" 1>&2
    exit 1
fi

if echo "$1" | grep -Eq '^-[0,1]+$|^[0,1]+$' 
     then
if [ $1 -lt 0 ]
then
    a=$(($1*-1))
    test=$((2#$a))
    echo "bin2dec($1)=-$test"
else
    test=$((2#$1))
    echo "bin2dec($1)=$test"
    fi
     else
	 echo "Error" 1>&2
	 exit 1
	 fi
exit 0
