#!/bin/sh
## db for shell in /home/jouvel_a/rendu/SHL_2016_shell
## 
## Made by Anthony jouvel
## Login   <jouvel_a@epitech.net>
## 
## Started on  Tue Jan  3 19:03:23 2017 Anthony jouvel
## Last update Tue Jan  3 19:03:24 2017 Anthony jouvel
##

if [ "$#" -ne 1 ]
then
    echo "USAGE: $0 filename" 1>&2
    echo "filename : line by line db file - each entry must be separated with a blank line" 1>&2
    echo "result : 1 line by record, order by field name" 1>&2
    exit 1
fi

file=$(cat $1)

categories=$(grep -E "\w+ : " $1 | cut -f1 -d: | sort -n)

categories_tab=(${categories// / })

i=1
y=1
true_categories_tab[0]=${categories_tab[0]}
last_element=${categories_tab[0]}

while [ $i -lt ${#categories_tab[@]} ]
do
    if [ ${categories_tab[$i]} != $last_element ]
    then
	true_categories_tab[$y]=${categories_tab[$i]}
	last_element=${categories_tab[$i]}
	y=$(($y+1))
    fi
    i=$(($i+1))
done

empty_lines=$(grep -n "^$" $1 | cut -f1 -d:)
empty_lines=(${empty_lines// / })

exit 0
