#!/bin/sh

if [[ "$#" -ne 3 ]]; then
    echo "USAGE: ./replace original_stringfile replace_stringfile file" 1>&2
    echo "Replace in file each string of original_stringfile by replace_stringfile" 1>&2
    exit 1
fi

