#!/bin/sh
## tree for shell in /home/jouvel_a/rendu/SHL_2016_shell
## 
## Made by Anthony jouvel
## Login   <jouvel_a@epitech.net>
## 
## Started on  Tue Jan  3 18:57:58 2017 Anthony jouvel
## Last update Tue Jan  3 23:17:30 2017 Anthony jouvel
##

if [ "$#" -ne 1 ]
then   echo "USAGE: $0 DirName" 1>&2
       exit 1
fi

echo "ERROR: $1 is not a directory" 1>&2
exit 1
