#!/bin/sh
## upcase_lowcase for shell in /home/jouvel_a/rendu/SHL_2016_shell
## 
## Made by Anthony jouvel
## Login   <jouvel_a@epitech.net>
## 
## Started on  Tue Jan  3 11:50:03 2017 Anthony jouvel
## Last update Tue Jan  3 11:50:05 2017 Anthony jouvel
##

if [ "$#" -eq 0 ];then
    echo "USAGE: $0 -l -u" 1>&2
    echo "-l : lowcase" 1>&2
    echo "-u : upcase" 1>&2
    exit 1
fi

for param in "$@"
do
    if [ $param != "-u" -a $param != "-l" ];then
	echo "ERROR: $param unknown option" 1>&2
	exit 1
    fi
done

if [ $param == "-u" ];then
    echo "`cat`"  | tr [a-z] [A-Z] 
else
    echo "`cat`"  | tr [A-Z] [a-z]
fi
exit 0
